In [66]:
import os
import numpy as np
import pandas as pd

In [67]:
# clean City of vancouver data to merge into doordash data
cityOfVancouver = pd.read_csv("data/business-licences.csv", sep=';')
cofV = pd.DataFrame(cityOfVancouver)
cofV = cofV[["BusinessName","BusinessTradeName", "PostalCode" , "Geom","geo_point_2d"]].rename(columns={
    'BusinessName': 'parent_company',
    'BusinessTradeName': 'name',
    'PostalCode': 'postal_code',
    'Geom': 'Geom',
    'geo_point_2d': 'geo_point_2d'
})
cofV

,parent_company,name,postal_code,Geom,geo_point_2d
0,299 Burrard Management Ltd,Fairmont Pacific Rim Hotel - Botanist,V6C 0B9,"{""coordinates"": [-123.116590608283, 49.2881583...","49.2881583053534, -123.116590608283"
1,Nuba Restaurant Group Inc,Nuba Cafe,V5T 1C8,"{""coordinates"": [-123.101706485945, 49.2679670...","49.2679670689207, -123.101706485945"
2,Takoyaki Enterprises Ltd,Toshi Sushi,V5T 4R2,"{""coordinates"": [-123.101748807393, 49.2570695...","49.2570695356725, -123.101748807393"
3,Chinatown Garden BBQ Restaurant Inc,Chinatown BBQ,V6A 1T3,"{""coordinates"": [-123.101491515653, 49.2801628...","49.2801628817922, -123.101491515653"
4,Vanall Restaurant Services Corp,Sushi Maro,V6B 2S2,"{""coordinates"": [-123.121996984635, 49.2750076...","49.2750076198637, -123.121996984635"
...,...,...,...,...,...
3380,Tamaru Shoten Marketing Corp,New Fuji,V6J 5B8,"{""coordinates"": [-123.146783549831, 49.2709298...","49.270929865845, -123.146783549831"
3381,Wall Financial Corporation,Sheraton Vancouver Wall Centre Hotel-Banquets,V6Z 2R9,"{""coordinates"": [-123.12653676373, 49.28011750...","49.2801175077101, -123.12653676373"
3382,Wall Financial Corporation,Sheraton Vancouver Wall Centre Hotel-Cafe One,V6Z 2R9,"{""coordinates"": [-123.12552501795, 49.28041148...","49.2804114853095, -123.12552501795"
3383,Jungle Room Inc,Jungle Room,V6G 2M3,"{""coordinates"": [-123.138057076679, 49.2899924...","49.2899924877426, -123.138057076679"
3384,Seaport City Restaurant Ltd (Mei Mai),Seaport City Restaurant,V5Z 4M5,"{""coordinates"": [-123.115860260146, 49.2637076...","49.2637076476411, -123.115860260146"

In [68]:
# Merge with yelp data for vancouver
yelpVan = pd.read_csv("data/vancouver_yelp_food.csv")
yelpVan = yelpVan[yelpVan["state"] == "BC"]
yelpVan = yelpVan.drop(["city","state","business_id","is_open", "BYOBCorkage", "Open24Hours"],axis=1)
yelpVan

,name,address,postal_code,latitude,longitude,stars_fair,stars,review_count,attributes,categories,...,DriveThru,GoodForDancing,DietaryRestrictions,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday
0,Bob Likes Thai Food,3755 Main St,V5V,49.251342,-123.101333,3.485632,3.5,169,"{'GoodForKids': 'True', 'Alcohol': ""u'none'"", ...","Restaurants, Thai",...,NaN,NaN,NaN,17:0-21:0,17:0-21:0,17:0-21:0,17:0-21:0,17:0-21:0,17:0-21:0,17:0-21:0
2,BC Liquor Store,1655 Davie Street,V6G 1W1,49.286111,-123.139524,2.500000,2.0,5,"{'BusinessParking': ""{'garage': False, 'street...","Beer, Wine & Spirits, Food",...,NaN,NaN,NaN,9:30-23:0,9:30-23:0,9:30-23:0,9:30-23:0,9:30-23:0,9:30-23:0,11:0-18:0
3,Let's Roll Custom Sushi Bar,"1184 Denman Street, Suite 104",V6G 2M9,49.286360,-123.140261,4.291667,4.5,31,"{'RestaurantsAttire': ""u'casual'"", 'HasTV': 'F...","Restaurants, Canadian (New), Sushi Bars, Ameri...",...,NaN,NaN,NaN,11:0-22:0,11:0-22:0,11:0-22:0,11:0-22:0,11:0-22:0,11:0-22:0,11:0-22:0
6,Little Caesars,7010 Kerr Street,V5S,49.219532,-123.040893,1.714286,1.0,9,"{'GoodForKids': 'True', 'RestaurantsReservatio...","Restaurants, Pizza",...,NaN,NaN,NaN,11:0-23:0,11:0-23:0,11:0-23:0,11:0-23:0,11:0-23:0,11:0-23:0,11:0-23:0
7,Jackson's Poultry,1689 Johnston St,V6H 3R9,49.272114,-123.134941,3.545455,4.0,6,"{'BusinessParking': ""{'garage': False, 'street...","Food, Specialty Food, Farmers Market, Butcher,...",...,NaN,NaN,NaN,9:0-19:0,9:0-19:0,9:0-19:0,9:0-19:0,9:0-19:0,9:0-19:0,9:0-19:0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6477,De Dutch,"1725 Robson St, Unit 1",V6G 1C9,49.291000,-123.134102,3.000000,3.0,78,"{'Alcohol': ""u'beer_and_wine'"", 'Ambience': ""{...","Modern European, Gluten-Free, Restaurants, Bre...",...,NaN,NaN,"{'dairy-free': False, 'gluten-free': True, 've...",8:0-15:0,8:0-15:0,8:0-15:0,8:0-15:0,8:0-15:0,8:0-15:0,8:0-15:0
6478,Baccano Osteria-Bar,1889 W 1st Avenue,V6J 5B8,49.270823,-123.147734,2.500000,2.0,5,"{'WiFi': ""u'paid'"", 'RestaurantsTakeOut': 'Tru...","Italian, Restaurants",...,NaN,NaN,NaN,17:0-22:0,17:0-22:0,17:0-22:0,17:0-22:0,17:0-23:0,17:0-23:0,17:0-21:30
6479,YiFang Taiwan Fruit Tea,3612 Kingsway,V5R 5M2,49.232031,-123.026117,3.410714,3.5,23,"{'BusinessParking': ""{'garage': False, 'street...","Bubble Tea, Juice Bars & Smoothies, Food",...,NaN,NaN,NaN,13:0-22:0,13:0-22:0,13:0-22:0,13:0-22:0,13:0-23:0,11:0-23:0,11:0-22:0
6480,Elysian Coffee,"1100 Burrard Street, Suite 102",V6Z 1Y9,49.279845,-123.127654,3.913793,4.0,53,"{'RestaurantsPriceRange2': '1', 'GoodForMeal':...","Coffee Roasteries, Breakfast & Brunch, Food, C...",...,NaN,NaN,NaN,7:0-18:0,7:0-18:0,7:0-18:0,7:0-18:0,7:0-18:0,9:0-16:0,9:0-16:0
6482,The North Face,2136 W 4th Avenue,V6K 1N6,49.268037,-123.153648,2.604167,2.5,19,"{'RestaurantsPriceRange2': '3', 'BikeParking':...","Sports Wear, Sporting Goods, Food, Shopping, F...",...,NaN,NaN,NaN,10:0-18:0,10:0-18:0,10:0-18:0,10:0-20:0,10:0-20:0,10:0-18:0,11:0-18:0

In [69]:
# Join the dataset
mergedVanEats = pd.merge(cofV, yelpVan, on='name', how='inner')
mergedVanEats = mergedVanEats[mergedVanEats["postal_code_x"] == mergedVanEats["postal_code_y"]]
mergedVanEats = mergedVanEats[["parent_company","name","postal_code_x","address","latitude","longitude","stars_fair","stars","review_count","categories","RestaurantsReservations","RestaurantsPriceRange2","NoiseLevel","OutdoorSeating","ByAppointmentOnly","DietaryRestrictions","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]]
mergedVanEats.columns = ["parent_company","name","postal_code","address","latitude","longitude","stars_fair","stars","review_count","categories","RestaurantsReservations","RestaurantsPriceRange2","NoiseLevel","OutdoorSeating","ByAppointmentOnly","DietaryRestrictions","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
mergedVanEats

,parent_company,name,postal_code,address,latitude,longitude,stars_fair,stars,review_count,categories,...,OutdoorSeating,ByAppointmentOnly,DietaryRestrictions,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday
0,Takoyaki Enterprises Ltd,Toshi Sushi,V5T 4R2,181 East 16th Avenue,49.256699,-123.101936,3.987952,4.0,410,"Sushi Bars, Restaurants, Japanese",...,False,NaN,NaN,NaN,16:0-20:0,16:0-20:0,16:0-20:0,16:0-20:0,16:0-20:0,NaN
1,Chinatown Garden BBQ Restaurant Inc,Chinatown BBQ,V6A 1T3,130 E Pender Street,49.280294,-123.101500,4.455090,4.5,162,"Barbeque, Chinese, Cantonese, Restaurants",...,False,False,NaN,0:0-0:0,11:0-19:0,11:0-19:0,11:0-18:0,11:0-19:0,11:0-19:0,11:0-19:0
3,Flying Fish Holdings Ltd,Ophelia,V5Y 1B8,165 W 2nd Avenue,49.269470,-123.108095,3.368421,3.5,14,"Mexican, Restaurants",...,True,NaN,NaN,16:0-23:0,16:0-23:0,16:0-23:0,16:0-23:0,16:0-23:0,16:0-23:0,16:0-22:0
5,China Noodle Restaurant (Joyce) Ltd,Kung Fu Noodle,V5R 4J9,5615 Harold Street,49.233490,-123.035229,3.833333,4.0,25,"Restaurants, Chinese, Noodles",...,NaN,NaN,NaN,11:0-21:30,11:0-21:30,NaN,11:0-21:30,11:0-21:30,11:0-21:30,11:0-21:30
6,1125352 BC Ltd,Tocador,V5T 3E6,2610 Main Street,49.261824,-123.100789,3.432432,3.5,32,"Cuban, Restaurants, Latin American, Cocktail B...",...,True,NaN,NaN,0:0-0:0,NaN,17:0-22:0,19:30-22:0,17:0-22:0,11:0-22:0,11:0-22:0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3537,1347429 BC Ltd,Ki-Isu Japanese Restaurant,V6Z 2R6,1275 Pacific Boulevard,49.273715,-123.123477,3.477477,3.5,106,"Japanese, Restaurants, Sushi Bars",...,True,NaN,NaN,11:30-21:15,11:30-21:15,11:30-21:15,11:30-21:15,11:30-21:15,11:30-21:15,11:30-21:15
3572,Pattison Food Group Ltd,Urban Fare,V6Z 2Y1,177 Davie Street,49.273545,-123.120561,3.481752,3.5,132,"Florists, Grocery, Flowers & Gifts, Food, Spec...",...,NaN,NaN,NaN,6:0-23:0,6:0-23:0,6:0-23:0,6:0-23:0,6:0-23:0,6:0-23:0,6:0-23:0
3574,Mizu Sushi Restaurant Inc,Mogu Fried Chicken,V5L 3W9,1012 Commercial Drive,49.275607,-123.069326,4.058824,4.5,12,"Chicken Shop, Japanese, Restaurants, Food Truc...",...,NaN,NaN,NaN,NaN,11:30-21:0,11:30-21:0,11:30-21:0,11:30-22:0,11:30-22:0,11:30-21:0
3580,Floata Seafood Restaurant (Chinatown) Ltd,Floata Seafood Restaurant,V6A 4E9,180 Keefer Street,49.279105,-123.100762,2.513228,2.5,184,"Seafood, Restaurants, Chinese, Dim Sum",...,False,NaN,NaN,8:0-22:0,8:0-22:0,8:0-22:0,8:0-22:0,8:0-22:0,8:0-22:0,8:0-22:0
3597,1459071 BC Ltd,Harbour Oyster + Bar,V5L 3X9,1408 Commercial Drive,49.271895,-123.069182,3.886364,4.0,39,"Fish & Chips, Nightlife, Seafood, Bars, Restau...",...,NaN,False,NaN,11:0-0:0,11:0-0:0,11:0-0:0,11:0-0:0,11:0-0:0,11:0-1:0,11:0-1:0

In [70]:
# Make sure the folder exists
os.makedirs("cleaned", exist_ok=True)

# Export the DataFrame to CSV
mergedVanEats.to_csv("cleaned/VancouverRestaurants.csv", index=False, encoding='utf-8')